export const INVESTOR_PROJECTS = [
  {
    id: "1",
    title: "Antalya Butik Otel Projesi",
    category: "Turizm",
    desc: "Antalya'da 80 odalı lüks butik otel inşaatı. A&D Global Work insan kaynakları desteğiyle eksiksiz personel temini.",
    location: "Antalya, Türkiye",
    budget: "€2.5M",
    roi: "%22 / yıl",
    duration: "18 ay",
    colorClass: " bg-gradient-to-br from-blue-600 to-blue-900",
  },
  {
    id: "2",
    title: "Kıbrıs Konut Kompleksi",
    category: "İnşaat",
    desc: "Kuzey Kıbrıs'ta 150 daireli yaşam kompleksi. Avrupa pasaportu fırsatıyla birlikte sunuluyor.",
    location: "Lefkoşa, Kıbrıs",
    budget: "€5M",
    roi: "%18 / yıl",
    duration: "24 ay",
    colorClass: " bg-gradient-to-br from-emerald-600 to-emerald-900",
  },
  {
    id: "3",
    title: "İspanya Agro-Turizm Çiftliği",
    category: "Tarım",
    desc: "İspanya'da organik tarım ve eko-turizm kombinasyonu. Sürdürülebilir gelir modeli.",
    location: "Valencia, İspanya",
    budget: "€1.2M",
    roi: "%15 / yıl",
    duration: "12 ay",
    colorClass: " bg-gradient-to-br from-amber-600 to-amber-900",
  },
  {
    id: "4",
    title: "Güneş Enerjisi Santrali",
    category: "Enerji",
    desc: "Türkiye'de 5 MW kurulu güce sahip güneş enerjisi santrali. Devlet teşvikli proje.",
    location: "Konya, Türkiye",
    budget: "€3M",
    roi: "%20 / yıl",
    duration: "8 ay",
    colorClass: " bg-gradient-to-br from-purple-600 to-purple-900",
  },
];
